crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016B_v1 --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016B_v2 --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016C --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016D --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016E --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016F --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016F1 --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016G --verboseErrors
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H --verboseErrors

