crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2017C-UL_14Oct20
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2017D-UL_14Oct20
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2017E-UL_14Oct20
crab status -d crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2017F-UL_14Oct20
